Add support for secure marks
DataDog/dd-native-iast-taint-tracking-js pull request #72
Opened 2023-06-30 11:22 UTC by uurien

### What does this PR do?

### Motivation

### Additional Notes

### Describe how to test your changes

### Checklist

- [ ] The CHANGELOG.md has been updated
- [ ] Unit tests have been updated and pass
- [ ] If known, an appropriate milestone has been selected

2023-07-05 07:42 UTC, hoolioh requested changes

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/range.h
> +    explicit Range(int start, int end, InputInfo *inputInfo, int secureMarks);
```suggestion
    explicit Range(int start, int end, InputInfo *inputInfo, secure_marks_t secureMarks);
```

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/range.h
> +    explicit Range(int start, int end, InputInfo *inputInfo, int secureMarks);
I'll also add before line 12 the type definition, e.g. `using secure_marks_t = uint32_t`. I think just for now we can use an `uint32_t` (4 bytes), later if we need to use more than 32 options then we can use a `std::bitset` which its minimum size is 8 bytes.

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/range.h
> +    int secureMarks;
```suggestion
    secure_marks_t secureMarks;
```

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/range.cc
> +Range::Range(int start, int end, InputInfo *inputInfo, int secureMarks) {
```suggestion
Range::Range(int start, int end, InputInfo *inputInfo, secure_marks_t secureMarks) {
```

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/string_resource.h
> +    // if string length < 10 then make a new one in order to avoid cache issues.
```suggestion
```

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/string_resource.h
> +    if (len == 1) {
```suggestion
    if (len == 1) {
        // Avoid string interning.
```

2023-07-05 07:42 UTC, hoolioh commented on src/tainted/transaction.h
> +    Range* GetRange(int start, int end, InputInfo *inputInfo, int secureMarks) {
```suggestion
    Range* GetRange(int start, int end, InputInfo *inputInfo, secure_marks_t secureMarks) {
```

2023-07-05 07:42 UTC, hoolioh commented on src/api/string_methods.cc
> +    int secureMarks = secureMarksArgument->IntegerValue(context).FromJust();
```suggestion
    unsigned int secureMarks = secureMarksArgument->IntegerValue(context).FromJust();
```

2023-07-05 07:42 UTC, hoolioh commented on src/api/string_methods.cc
> +                int oSecureMarks = oRange->secureMarks;
```suggestion
                auto oSecureMarks = oRange->secureMarks;
```

2023-07-05 07:42 UTC, hoolioh commented on test/js/secure-marks.spec.js
> +  const id = '666'
```suggestion
  const id = TaintedUtils.createTransaction('666')
```

2023-07-05 07:42 UTC, hoolioh commented on test/js/secure-marks.spec.js
> +
```suggestion

it('Wrong arguments', function () {
    assert.throws(function () {
      TaintedUtils.addSecureMarksToTaintedString(id, value)
    }, Error)
  })
```

2023-07-05 07:42 UTC, hoolioh commented on test/js/secure-marks.spec.js
I think it will also better to add a test testing the upper limit of of the secure marks so it can check that there is no problem with signedness and expect what will be the max bit size.

2023-07-05 09:42 UTC, uurien commented on test/js/secure-marks.spec.js
added

2023-07-18 11:33 UTC, hoolioh approved these changes

2023-07-19 08:20 UTC, merged